/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  LlmEventType,
  type LlmEvent,
  type LlmTextDeltaEvent,
  type LlmThoughtDeltaEvent,
  type LlmToolCallRequestEvent,
  type LlmFinishedEvent,
  type LlmMessageEndEvent,
  type LlmErrorEvent,
  type LlmFinishReason,
} from './events.js';
import type { LlmTokenUsage, LlmToolCallContent } from './types.js';

/**
 * Result of assembling a stream of events into a complete message.
 */
export interface AssembledMessage {
  /** Assembled text content */
  text: string;
  /** Assembled thought/reasoning content */
  thought: string;
  /** Collected tool calls */
  toolCalls: LlmToolCallContent[];
  /** Token usage information */
  usage?: LlmTokenUsage;
  /** Finish reason if stream is complete */
  finishReason?: LlmFinishReason;
  /** Whether the stream is complete */
  isComplete: boolean;
  /** Error if any occurred */
  error?: Error | string;
}

/**
 * Assembles stream events into a complete message.
 *
 * This class accumulates streaming events (text deltas, thought deltas,
 * tool calls, etc.) and provides methods to retrieve the assembled content.
 *
 * **Handled Events:**
 * - `TextDelta` - Concatenated into text
 * - `ThoughtDelta` - Concatenated into thought
 * - `ToolCallRequest` - Collected as tool calls
 * - `Finished` / `MessageEnd` - Marks stream complete, captures usage
 * - `Error` - Captures error and marks stream complete
 *
 * **Design Decision:** `ToolCallResponse` and `ToolCallConfirmation` events
 * are intentionally not processed by StreamAssembler. These events represent
 * tool execution results that flow back into the conversation context, not
 * content generated by the model. They should be handled by the orchestration
 * layer that manages the tool execution lifecycle.
 *
 * @example
 * ```ts
 * const assembler = new StreamAssembler();
 *
 * for await (const event of stream) {
 *   assembler.processEvent(event);
 * }
 *
 * const message = assembler.getAssembledMessage();
 * console.log(message.text);
 * ```
 *
 * @see docs/ai_adapter/03-technical-design.md §3.5
 */
export class StreamAssembler {
  private text = '';
  private thought = '';
  private toolCalls: LlmToolCallContent[] = [];
  private usage?: LlmTokenUsage;
  private finishReason?: LlmFinishReason;
  private complete = false;
  private error?: Error | string;

  /**
   * Process a stream event and accumulate its content.
   *
   * @param event - Stream event to process
   * @returns This assembler for chaining
   */
  processEvent(event: LlmEvent): this {
    switch (event.type) {
      case LlmEventType.TextDelta:
        this.handleTextDelta(event);
        break;

      case LlmEventType.ThoughtDelta:
        this.handleThoughtDelta(event);
        break;

      case LlmEventType.ToolCallRequest:
        this.handleToolCallRequest(event);
        break;

      case LlmEventType.Finished:
        this.handleFinished(event);
        break;

      case LlmEventType.MessageEnd:
        this.handleMessageEnd(event);
        break;

      case LlmEventType.Error:
        this.handleError(event);
        break;

      // Other event types are ignored for now
      default:
        // No-op for unhandled events
        break;
    }

    return this;
  }

  /**
   * Get the assembled text content.
   */
  getText(): string {
    return this.text;
  }

  /**
   * Get the assembled thought/reasoning content.
   */
  getThought(): string {
    return this.thought;
  }

  /**
   * Get the collected tool calls.
   */
  getToolCalls(): LlmToolCallContent[] {
    return [...this.toolCalls];
  }

  /**
   * Get token usage information.
   */
  getUsage(): LlmTokenUsage | undefined {
    return this.usage;
  }

  /**
   * Get the error if any occurred.
   */
  getError(): Error | string | undefined {
    return this.error;
  }

  /**
   * Check if the stream is complete.
   */
  isComplete(): boolean {
    return this.complete;
  }

  /**
   * Get the fully assembled message.
   */
  getAssembledMessage(): AssembledMessage {
    return {
      text: this.text,
      thought: this.thought,
      toolCalls: [...this.toolCalls],
      usage: this.usage,
      finishReason: this.finishReason,
      isComplete: this.complete,
      error: this.error,
    };
  }

  /**
   * Reset the assembler to its initial state.
   */
  reset(): void {
    this.text = '';
    this.thought = '';
    this.toolCalls = [];
    this.usage = undefined;
    this.finishReason = undefined;
    this.complete = false;
    this.error = undefined;
  }

  // ============================================================================
  // Private Event Handlers
  // ============================================================================

  private handleTextDelta(event: LlmTextDeltaEvent): void {
    this.text += event.text;
  }

  private handleThoughtDelta(event: LlmThoughtDeltaEvent): void {
    this.thought += event.thought;
  }

  private handleToolCallRequest(event: LlmToolCallRequestEvent): void {
    this.toolCalls.push({
      type: 'tool_call',
      id: event.callId,
      name: event.name,
      arguments: event.args,
    });
  }

  private handleFinished(event: LlmFinishedEvent): void {
    this.complete = true;
    if (event.usage) {
      this.usage = event.usage;
    }
    if (event.finishReason) {
      this.finishReason = event.finishReason;
    }
  }

  private handleMessageEnd(event: LlmMessageEndEvent): void {
    this.complete = true;
    if (event.usage) {
      this.usage = event.usage;
    }
  }

  private handleError(event: LlmErrorEvent): void {
    this.error = event.error;
    this.complete = true; // Error terminates the stream
  }
}
